### ISSUE TITLE
yarn test not running in CRNA example

### ISSUE THREAD

**Issue by amcvitty** [connectdotz/yarn-nohoist-examples#1]
If I build this project with a straight `yarn install`, then run `yarn ios` it runs correctly as described. 

https://github.com/connectdotz/yarn-nohoist-examples/tree/master/workspaces-examples/react-native/rn-expo

However, running `yarn test` doesn't do anything because the "test" target in the sub-package is still 

`"test": "node node_modules/jest/bin/jest.js"`

and the jest package has not been included in nohoist. 

I managed to fix it by adding 

```
      "**/jest-expo",
      "**/jest-expo/**"
```
to the package.json at the top. Reporting as an issue rather than a PR because I'm not sure this is the right thing to do here.

**Comment by connectdotz** [comment]
thanks for spotting this. Indeed that was missed... Your fix worked 👍 , feel free to submit a PR.

**Comment by amcvitty** [comment]
Done - see #2 

Also - thank you for your work on this nohoist concept. I see you contributed a lot of work to yarn to make it possible. I am incorporating this into our app, which has a React web and a React Native component in two packages.

**Comment by connectdotz** [comment]
it was fun to do something that matters. Now you are too!
