### ISSUE TITLE
Symlinks

### ISSUE THREAD

**Issue by goodmind** [connectdotz/yarn-nohoist-examples#3]
Does multiple packages also works?

**Comment by connectdotz** [comment]
you mean multiple workspaces, such as in [this example](https://github.com/connectdotz/yarn-nohoist-examples/tree/master/workspaces-examples/universal-cipher)?

**Comment by goodmind** [comment]
@connectdotz Thanks! What if I use TypeScript/Flow? Do I need to build each package independently?

**Comment by goodmind** [comment]
Also do I need to add all react-native project dependencies to nohoist?

**Comment by connectdotz** [comment]
whether you use js, typescript or flow should not impact how nohoist is setup. At the end of the day, both ts and flow convert your code to js, all are operated as js code at run time

**Comment by connectdotz** [comment]
@goodmind I hope your project is all going well now, I am going to close this issue as there is nothing to do at this point. Feel free to open new ones if needed.
