### ISSUE TITLE
Fails with other dependencies in React Native

### ISSUE THREAD

**Issue by cmcewen** [connectdotz/yarn-nohoist-examples#4]
I've been struggling to get workspaces running with React Native and stumbled across this repo. I replicated the setup in my own project but kept running into errors, until I realized the same problem would occur here.

Adding any dependency that gets hoisted to the top node_modules fails - for example, `react-redux` which is pure JS so doesn't need to be in the RN repo.

I get the following error:
```
Looking for JS files in
   /Users/cmcewen/code/yarn-nohoist-examples/workspaces-examples/universal-cipher/packages/RNCipher
   /Users/cmcewen/code/yarn-nohoist-examples/workspaces-examples/universal-cipher/packages/cipher-core 


Metro Bundler ready.

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `react-redux` from `/Users/cmcewen/code/yarn-nohoist-examples/workspaces-examples/universal-cipher/packages/RNCipher/App.js`: Module does not exist in the module map or in these directories:
  /Users/cmcewen/code/yarn-nohoist-examples/workspaces-examples/universal-cipher/node_modules
```

You can replicate it using this repo: https://github.com/cmcewen/yarn-nohoist-examples/tree/react-redux

**Comment by connectdotz** [comment]
looks like a metro issue, you can work around by providing explicit module roots via the rn-cli.config.js, such as:

```
"use strict";

var path = require("path");
const cwd = path.resolve(__dirname);

var config = {
  getProjectRoots() {
    return getRoots();
  },
  getAssetRoots() {
    return getRoots();
  },
  extraNodeModules: {
    crypto: path.resolve(cwd, "./node_modules/react-native-crypto"),
    stream: path.resolve(cwd, "./node_modules/react-native-stream"),
    randombytes: path.resolve(cwd, "./node_modules/react-native-randombytes"),
    vm: path.resolve(cwd, "./node_modules/vm-browserify")
  }
};

function getRoots() {
  return [
    cwd, // current directory
    path.resolve(cwd, "../..") // project directory
  ];
}

module.exports = config;

```

let me know if it works for you. good luck.

**Comment by connectdotz** [comment]
I have also updated the example to include multi-root support so the future fork will not bump into the same issue. 

Thanks for raising the issue, I am going to close it with the PR #5.
