### ISSUE TITLE
Monorepo with create-react-native-app

### ISSUE THREAD

**Issue by osdiab** [connectdotz/yarn-nohoist-examples#7]
Maybe I'm missing something about how this should work, but I'm trying to set up a monorepo with my own project (so that I can share code between my mobile/web apps and my api). The mobile app already is partially written so I'm copying it into this monorepo as a package.

But when I follow the nohoist directions then run `yarn start` in the `mobile-app` package, I get a bunch of errors as below. Do I need to make sure all dependencies of my mobile app are not hoisted or something? 

```
***ERROR STARTING PACKAGER***
Warning: 'es6-symbol' dependency is not installed.
Warning: 'immutable' dependency is not installed.
Warning: 'react-native-camera' dependency is not installed.
Warning: 'react-native-elements' dependency is not installed.
Warning: 'react-redux' dependency is not installed.
Warning: 'redux' dependency is not installed.
Warning: 'redux-persist' dependency is not installed.
Warning: 'redux-persist-transform-immutable' dependency is not installed.
Warning: 'redux-thunk' dependency is not installed.
```

This is what my monorepo package.json looks like (I use `react-native-scripts-ts` for typescript support):

```
{
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*"
    ],
    "nohoist": [
      "**/react-native/**",
      "**/react-native",
      "**/react-native-scripts-ts",
      "**/react-native-scripts-ts/**",
      "**/expo",
      "**/expo/**"
    ]
  }
}
```

Would love a hint, it'd be pretty cool if I could make this work!

**Comment by connectdotz** [comment]
react-native beyond the basic init is not trivial, you can check out the [react-native-cipher](https://github.com/connectdotz/yarn-nohoist-examples/tree/master/workspaces-examples/universal-cipher) example to see if it helps you in getting other dependencies into react-native app.

**Comment by osdiab** [comment]
Ah I didn’t realize that universal cipher was demonstrating just that. Still seems pretty hacky, I think I’ll wait to see if better monorepo support ever gets introduced. Thanks!

**Comment by jedrichards** [comment]
@osdiab Somebody has put together a demo monorepo incorporating CRNA (Expo) apps, CRA web apps and generic tools package. Haven't tried it myself, but it looks solid on first inspection.

https://github.com/viewstools/yarn-workspaces-cra-crna
